import {
    defineConfig
} from 'vite'
import {resolve} from "path";
import viteSheetPlugin from "./sheetPlugin.js";
import vitePluginString from 'vite-plugin-string'

export default defineConfig({
    resolve: {
        alias: {
            "fastclick": resolve(__dirname, "./src/vendor/fastclick.js"),
            "three": resolve(__dirname, "./src/vendor/three.module.js"),
            "abs-svg-path": resolve(__dirname, "./src/node_modules/abs-svg-path"),
            "adaptive-bezier-curve": resolve(__dirname, "./src/node_modules/adaptive-bezier-curve"),
            "an-array": resolve(__dirname, "./src/node_modules/an-array"),
            "animejs": resolve(__dirname, "./src/node_modules/animejs/lib/anime.es.js"),
            "array-almost-equal": resolve(__dirname, "./src/node_modules/array-almost-equal"),
            "array-flat-polyfill": resolve(__dirname, "./src/node_modules/array-flat-polyfill"),
            "bezier-easing": resolve(__dirname, "./src/node_modules/bezier-easing/src/index.js"),
            "bound-points": resolve(__dirname, "./src/node_modules/bound-points/bounds.js"),
            "browser-media-mime-type": resolve(__dirname, "./src/node_modules/browser-media-mime-type"),
            "gl-vec2": resolve(__dirname, "./src/node_modules/gl-vec2"),
            "gl-vec4": resolve(__dirname, "./src/node_modules/gl-vec4"),
            "camera-project": resolve(__dirname, "./src/node_modules/camera-project"),
            "canvas-sketch-util": resolve(__dirname, "./src/node_modules/canvas-sketch-util"),
            "d3-delaunay": resolve(__dirname, "./src/node_modules/d3-delaunay/src/index.js"),
            "d3-polygon": resolve(__dirname, "./src/node_modules/d3-polygon/src/index.js"),
            "d3-quadtree": resolve(__dirname, "./src/node_modules/d3-quadtree/src/index.js"),
            "decode-uri-component": resolve(__dirname, "./src/node_modules/decode-uri-component"),
            "deep-clone": resolve(__dirname, "./src/node_modules/deep-clone"),
            "defined": resolve(__dirname, "./src/node_modules/defined"),
            "delaunator": resolve(__dirname, "./src/node_modules/delaunator"),
            "earcut": resolve(__dirname, "./src/node_modules/earcut/src/earcut.js"),
            "eases": resolve(__dirname, "./src/node_modules/eases"),
            "euclidean-distance": resolve(__dirname, "./src/node_modules/euclidean-distance"),
            "events": resolve(__dirname, "./src/node_modules/events/events.js"),
            "fast-2d-poisson-disk-sampling": resolve(__dirname, "./src/node_modules/fast-2d-poisson-disk-sampling/src/fast-poisson-disk-sampling.js"),
            "float-hsl2rgb": resolve(__dirname, "./src/node_modules/float-hsl2rgb"),
            "float-rgb2hsl": resolve(__dirname, "./src/node_modules/float-rgb2hsl"),

            "global": resolve(__dirname, "./src/node_modules/global"),
            "howler": resolve(__dirname, "./src/node_modules/howler/dist/howler.js"),
            "inherits": resolve(__dirname, "./src/node_modules/inherits/inherits_browser.js"),
            "is-dom": resolve(__dirname, "./src/node_modules/is-dom"),
            "is-function": resolve(__dirname, "./src/node_modules/is-function"),
            "is-object": resolve(__dirname, "./src/node_modules/is-object"),
            "is-window": resolve(__dirname, "./src/node_modules/is-window"),
            "lerp": resolve(__dirname, "./src/node_modules/lerp"),
            "lerp-array": resolve(__dirname, "./src/node_modules/lerp-array"),
            "load-script": resolve(__dirname, "./src/node_modules/load-script"),
            "mouse-wheel": resolve(__dirname, "./src/node_modules/mouse-wheel/wheel.js"),
            "normalize-path-scale": resolve(__dirname, "./src/node_modules/normalize-path-scale"),
            "object-assign": resolve(__dirname, "./src/node_modules/object-assign"),
            "own-enumerable-keys": resolve(__dirname, "./src/node_modules/own-enumerable-keys"),
            "parse-headers": resolve(__dirname, "./src/node_modules/parse-headers/parse-headers.js"),
            "parse-svg-path": resolve(__dirname, "./src/node_modules/parse-svg-path"),
            "parse-unit": resolve(__dirname, "./src/node_modules/parse-unit"),
            "point-in-polygon": resolve(__dirname, "./src/node_modules/point-in-polygon"),
            "porter-stemmer": resolve(__dirname, "./src/node_modules/porter-stemmer/porter.js"),
            "process": resolve(__dirname, "./src/node_modules/process"),
            "query-string": resolve(__dirname, "./src/node_modules/query-string"),
            "rbush": resolve(__dirname, "./src/node_modules/rbush/rbush.min.js"),
            "right-now": resolve(__dirname, "./src/node_modules/right-now/browser.js"),
            "robust-predicates": resolve(__dirname, "./src/node_modules/robust-predicates"),
            "simple-media-element": resolve(__dirname, "./src/node_modules/simple-media-element"),
            "simplex-noise": resolve(__dirname, "./src/node_modules/simplex-noise/simplex-noise.js"),
            "simplify-path": resolve(__dirname, "./src/node_modules/simplify-path"),
            "split-on-first": resolve(__dirname, "./src/node_modules/split-on-first"),
            "stackblur": resolve(__dirname, "./src/node_modules/stackblur"),
            "strict-uri-encode": resolve(__dirname, "./src/node_modules/strict-uri-encode"),
            "svelte": resolve(__dirname, "./src/node_modules/svelte/"),
            "svg-path-contours": resolve(__dirname, "./src/node_modules/svg-path-contours"),
            "three-quaternion-from-normal": resolve(__dirname, "./src/node_modules/three-quaternion-from-normal"),
            "tinyqueue": resolve(__dirname, "./src/node_modules/tinyqueue"),
            "to-px": resolve(__dirname, "./src/node_modules/to-px/browser.js"),
            "tween-base": resolve(__dirname, "./src/node_modules/tween-base"),
            "tween-objects": resolve(__dirname, "./src/node_modules/tween-objects"),
            "tween-ticker": resolve(__dirname, "./src/node_modules/tween-ticker"),
            "unlerp": resolve(__dirname, "./src/node_modules/unlerp"),
            "vec2-copy": resolve(__dirname, "./src/node_modules/vec2-copy"),
            "web-audio-player": resolve(__dirname, "./src/node_modules/web-audio-player"),
            "xhr": resolve(__dirname, "./src/node_modules/xhr"),
            "xhr-progress": resolve(__dirname, "./src/node_modules/xhr-progress"),
            "xtend": resolve(__dirname, "./src/node_modules/xtend/immutable.js"),


        },
    },
    plugins: [viteSheetPlugin(), vitePluginString()]
})
